<?php
/** @var \MageSuite\ProductVariants\Block\Product\VariantSwitcher $block */
$variants = $block->getVariants();
$label = $block->getLabel() ?? __('Variants');
?>
<div class="cs-product-variants">
    <div class="cs-product-variants__label"><?= $label ?></div>
    <div class="cs-product-variants__content">
        <div 
            class="cs-product-variants__trigger"
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            data-trigger-keypress-button="true"
        >
            <div class="cs-product-variants__variant">
                <img class="cs-product-variants__variant-image" src='<?= $variants[0]->getImageUrl() ?>' />
                <?= $variants[0]->getVariantName() ?: $variants[0]->getShortName() ?>
            </div>
        </div>
        <div class="cs-product-variants__list" data-target="dropdown">
            <?php foreach ($variants as $variant): ?>
                <div class="cs-product-variants__variant">
                    <a class="cs-product-variants__variant-link" href="<?= $variant->getUrl() ?>">
                        <img class="cs-product-variants__variant-image" src='<?= $variant->getImageUrl() ?>' />
                        <?= $variant->getVariantName() ?: $variant->getShortName() ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>    
</div>
